### ISSUE TITLE
Support for Harvard machine architecture

### ISSUE THREAD

**Issue by marcinbugaj** [Orbis-Tertius/libbootstrap#11] opened 2022-03-29 11:20 UTC
That requires changes to compiler/linker/linker script/startup assembly code

**Comment by marcinbugaj** [comment] 2022-03-31 08:37
@morganthomas , @ursi 

With the current instruction set it may be difficult to implement Harvard machine. Let's suppose a program uses an array of constant integer coefficients. Those coefficients are part of the program thus are loaded to program address space. During program execution those coefficients need to be accessed (and treated as data). TinyRAM 2.0 does not specify any instruction that allows the contents of the instruction memory to be accessed as data. The aforementioned instruction turns Harvard machine into Modified Harvard machine (https://en.wikipedia.org/wiki/Modified_Harvard_architecture). In fact all modern non-von Neumann machines are Modified Harvard machines.

The question is if such instruction can be implemented in arithmetic circuit. Wouldn't it of the same difficulty as turning it into fully fledged von Neumann machine?

**Comment by moreSocratic** [comment] 2022-03-31 10:37
> The question is if such instruction can be implemented in arithmetic circuit. Wouldn't it of the same difficulty as turning it into fully fledged von Neumann machine?

It would depend on if we needed writes.
Adding an instruction for writing to program memory would be at least as difficult as adapting the paper to a von Neumann to TinyRAM.
Only adding an instruction for reading from program memory is unlikely to be overly difficult. However, it's not ideal, since it would significantly increase our circuits size.

> Let's suppose a program uses an array of constant integer coefficients. Those coefficients are part of the program thus are loaded to program address space. During program execution those coefficients need to be accessed (and treated as data).

Per the TinyRAM 2.0hv spec program space consists only of an array of instructions. The only way for the program space to contain data is as immediate values in `mov` or `cmov` instructions. An array of constant integer coefficients should go on the primary input tape, which is read by the  TinyRAM 2.0 preamble into the data address space.

Beyond modern convention, why should we prefer a Modified Harvard architecture over a pure Harvard architecture?

**Comment by marcinbugaj** [comment] 2022-03-31 11:40
Writes to program memory are not needed - only reads. That is a distinctive feature of Modified Harvard architecture. That would imply deviating from the original TinyRAM spec or rather trade-off between Harvard and von Neuman machines presented in the original spec.

I've got the impression that the primary input tape wasn't designed for this use case. A tinyRAM program alongside with primary input tape is public (known to a verifier). Auxiliary input tape is private - not necessarily known to a verifier. Auxiliary input tape can be seen as a secret. Thus primary and auxiliary tapes parameterize some relation to be proven to hold. Constants in question should be part of the relation itself (or rather tinyRAM code that expresses it) - not part of tapes. E.g. in relation `primary_tape[0] == 3 * auxiliary_tape[0]` the number `3` is part of tinyRAM program.

> Beyond modern convention, why should we prefer a Modified Harvard architecture over a pure Harvard architecture?

Efficiency. Let's suppose that array constant integers need to be indexed by a runtime value. Then the array needs to be copied from program memory to data memory by the means of sequence of *store* instructions: (`store dst_address, const`) even before program starts. That is pretty inefficient. With modified Harvard the array can be addressed directly in program memory. Not to mention that compiler implementation is simpler.

**Comment by morganthomas** [comment] 2022-03-31 12:05
Constants should not go on the primary input tape. The primary input tape is for the public input specifying the statement to be checked by the TinyRAM program. Constants must be compiled into the program. Perhaps the best solution here, which will not increase the circuit size, at the cost of increasing compiler output size, is to add startup code to a TinyRAM program containing array constants which loads those constants into RAM. I think the other approaches being discussed are worth considering but I wanted to suggest this one as I didn't see it suggested yet. Let's try and arrive at a consensus about what to do here. @marcinbugaj @moreSocratic @ursi

**Comment by moreSocratic** [comment] 2022-03-31 12:17
To clarify when I say:
>  "Only adding an instruction for reading from program memory is unlikely to be overly difficult. However, it's not ideal, since it would significantly increase our circuits size."

I'm referring to an instruction that would read a word from program memory to a register. Even then it would be good to limit this to odd words such that only field `#6` of the instructions binary encoding could be read. I am not referring to making the program address space support arbitrary data layouts. allowing elements other than instructions to live in the program address space breaks too many relations to be practical.

Loading constants into RAM at startup sounds like good solution.

**Comment by morganthomas** [comment] 2022-03-31 12:26
@marcinbugaj , I gave it some more thought and I feel like my proposed solution (which would not be an efficient solution to run on hardware) is likely to be the most cost effective and efficient solution of the ones proposed. What do you think?

**Comment by marcinbugaj** [comment] 2022-03-31 13:20
Without instruction that reads program memory as data the solution proposed by @morganthomas is equivalent to the proposed by me because the only way to transfer constants to data memory is by sequence of store instructions:

> Efficiency. Let's suppose that array constant integers need to be indexed by a runtime value. Then the array needs to be copied from program memory to data memory by the means of sequence of store instructions: (store dst_address, const) even before program starts.

In my approach those are generated by the compiler. @morganthomas , is it what you meant?

**Comment by marcinbugaj** [comment] 2022-03-31 13:23
@moreSocratic , the proposed instructions would behave exactly like the existing `load.w` and `load.b` instructions but operate on program address space. Yes, all in all I think that the destination operand could be omitted (assuming that the destination register is fixed).

**Comment by morganthomas** [comment] 2022-03-31 13:36
@marcinbugaj , yes, you understand my meaning correctly. It sounds like we are converging on a consensus here, but the only open question is do we want to add an additional instruction for reading from program memory? I don't see much of a case for adding such an instruction right now, though. The only reason I can see for doing so would be to allow for a more efficient representation of programs with large arrays of constants; but this assumes that the result would be more efficient, even after accounting for the cost of the added circuit size. I find it unlikely that this would be an improvement overall, since the extra circuit size would impact all programs but could only benefit programs with large arrays of constants. So if nobody has any further arguments to present, let's go with the approach of compiling array constants into sequences of store instructions.

**Comment by marcinbugaj** [comment] 2022-03-31 13:53
Ok. Agreed :)

**Comment by marcinbugaj** [comment] 2022-04-01 15:20
Bad news. IMO transitioning to pure Harvard architecture is not possible with llvm framework. All supported platforms are at least modified Harvard architectures. To my understanding, long story short: setting data memory with constants fits:
- neither code generation stage because it requires linking information
- nor linking stage because it requires code generation.

I reached out to llvm developer on discord and waiting for an answer.

**Comment by moreSocratic** [comment] 2022-04-01 17:06
To clarify: the issue we cannot transform LLVM constants into sequences of instruction placed in the preamble?

I'm looking into how the LLVM side of things constrains solutions.

It looks like we could have two different `DataLayout`s, so our data memory could remain byte addressed words of `W` bits, while our program memory could be word addressed words of `2W` bits. This would require an instruction that would read into two registers, which may not be viable. And would come at a cost in complexity and circuit size.
 
Otherwise we just bit the bullet and do a von Neumann, despite the substantial cost.

If at all possible a pure Harvard is greatly preferred. Hopefully the LLVM devs will have a work around.

**Comment by marcinbugaj** [comment] 2022-04-04 11:29
LLVM devs haven't responded yet. I'm looking into a solution that looks promising.

Back to the topic of a new instruction. Instruction that: treats instruction memory as data and loads register with a content of the instruction memory (read only). **Is the circuitry cost of such instruction higher that the cost of e.g. `add` instruction?** In order to execute such instruction one has to read program memory (as data) and then decode the instruction. The only difference is in operational effect of an instruction. In case of `add` it's adding the content of two registers. In case of proposed instruction is yet another program memory access and copying the content of it into a register.

>  so our data memory could remain byte addressed words of W bits

Even now data memory is assumed to be addressable by words and by individual bytes (`load.w`/`load.b` instructions). Does the same addressing scheme for program memory incurs (much) higher circuitry complexity?

General question: why is the von Neuman architecture more costly that Harvard?

**Comment by moreSocratic** [comment] 2022-04-04 12:25
> Instruction that: treats instruction memory as data and loads register with a content of the instruction memory (read only).
> Is the circuitry cost of such instruction higher that the cost of e.g. add instruction?

Yes, it is higher. it's best not to think of the halo 2 circuit costs as analogous to costs in traditional computing.
In this case it will require a canonical op code to exist in the Prog table, and some degree of special casing in the `Exe` table. I don't have an exact answer for how much complexity this would add.

> Even now data memory is assumed to be addressable by words and by individual bytes (load.w/load.b instructions). Does the same addressing scheme for program memory incurs (much) higher circuitry complexity?

The addition of `load.b`, and `store.b` to TinyRam 2.0 does incur a cost. We have not yet implemented them, and there are several candidate implementation methods, so the cost is not yet well quantified.

_Program memory_ is not a concept that presently exists in our circuit. We just have a list of instructions and meta data used to prove the execution of these instructions.

**Comment by moreSocratic** [comment] 2022-04-04 14:11
One potential solution that would allow LLVM to generate modified Harvard (read only) programs is trace rewriting.

LLVM could write constants into program memory. Then prior to proof generation in the tiny-ram-halo2 crate we could rewrite those constants as stores, and insert them into the preamble, just like Morgan had proposed (except in tiny-ram-halo2 not LLVM). At which point we would only have to delete them from program memory and rewrite loads from program memory to data memory.

Rewriting traces is already one of the potential solutions for implementing `load.b`, and `store.b`. Think micro-ops in a x86. Although this is unlikely to be the solution we go with.

**Comment by marcinbugaj** [comment] 2022-04-04 17:38
As for trace rewriting. Inserting code to a preamble changes offsets which makes program incorrect. That's because absolute addressing is used in jumps. Instead of inserting on could **call** a function that populates globals and constants. That function would have to be built outside of llvm toolchain and, once defined, late linked to build final executable. IMO this approach is error prone and feels very awkward.

There are multiple solutions and this is a subjective list of most viable approaches:
1. Adding 'load as data from program memory' instruction.
If support for additional opcode is the only issue then we can afford it. I would put this ticket on hold until it becomes clear what is the cost of adding this instruction really is. Arguably constants rich application may benefit from saved copy instructions. Also, see [this ticket](https://github.com/Orbis-Tertius/libbootstrap/issues/9) for instruction set refinements.
2. Override `AsmPrinter::emitGlobalConstant` method to produce sequence of `store` instructions.
That's the approach I was pursuing today. It's quirky, too. When creating those instruction one has to obey ABI rules for tables, struct etc. The code for it is already there but it's big and tightly coupled with spilling to globals and constants to appropriate sections. I still don't know if it's doable.
3. Variations on 'trace rewriting' theme.

@morganthomas , @moreSocratic I'd like to put this ticket on hold until we find out more about the cost of adding the instruction.

**Comment by moreSocratic** [comment] 2022-04-04 18:01
> If support for additional opcode is the only issue then we can afford it.
This is not the only cost.

Can you control the placement of constants in program memory such that all constants are placed after instructions with no interleaving (E.g. `[preamble, program instructions, constants]`)?

**Comment by marcinbugaj** [comment] 2022-04-05 11:02
Yes, it's exactly done in this way.

**Comment by morganthomas** [comment] 2022-04-05 14:32
I am not sure what would be the best thing to do here. Overall, I would prefer to squeeze as much complexity as possible out of the circuit. I feel that it's better to have a larger up front engineering cost to get a solution that is efficient. But I also feel that it's better to have a solution that's correct but not efficient than a solution that is efficient but not correct.

It's true that trace rewriting modifies instruction addresses in-memory, and it's true that this is a potential source of error. I don't know that we can guarantee semantics preservation in trace rewriting. 

I am not sure how confident we can be in an approach based on overriding `AsmPrinter::emitGlobalConstant`.

In consideration of these issues, I feel that all paths are worth exploring at this time. @moreSocratic , I feel like it would be good to further explore the trace rewriting approach and see if it can be made semantics preserving, and failing that, it would be good to get specific about what changes to the circuit are required to support a different architecture that we know how to codegen for. I am willing to work on these things with you. @marcinbugaj , I would leave it to you to judge if further investigating the overriding `emitGlobalConstant` approach is the best use of your time right now or not.

**Comment by morganthomas** [comment] 2022-06-13 15:42
Closed as duplicate of #21

**Closed as completed** 2022-06-13 15:41 UTC
